# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhManager < Formula
  desc ""
  homepage "https://maxence.maireaux.fr"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.1.0/gh-manager_darwin-amd64.tar.gz"
      sha256 "d45818c61edbcb32b7c6b44729e3a6c1c43046d8492fe9622f42840d6e669174"

      def install
        bin.install "gh-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.1.0/gh-manager_darwin-arm64.tar.gz"
      sha256 "1cbadedff8b1631052319c4ab0a3d70ec0da2f45d94eaf601d229500d4159add"

      def install
        bin.install "gh-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.1.0/gh-manager_linux-arm64.tar.gz"
      sha256 "8564b6d7935a38955acef6d25e1ac97b9dd944c5e954e6d8baf1e56508974548"

      def install
        bin.install "gh-manager"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.1.0/gh-manager_linux-amd64.tar.gz"
      sha256 "a65acda4d307c9a9f4b2fb9d85bbc723d1001e0399499efd12d4612d7be7a67e"

      def install
        bin.install "gh-manager"
      end
    end
  end

  test do
    system "#{bin}/gh-manager version"
  end
end
