# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhManager < Formula
  desc ""
  homepage "https://maxence.maireaux.fr"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.2.0/gh-manager_darwin-arm64.tar.gz"
      sha256 "b55c57488ea12778b094c2970d6660ca16a97dbc57922d85f34b6a5286aeefff"

      def install
        bin.install "gh-manager"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.2.0/gh-manager_darwin-amd64.tar.gz"
      sha256 "06d7d3e0cc5a22613c254f99d2af786bfe26c79e64f08882758ea31e72abeb80"

      def install
        bin.install "gh-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.2.0/gh-manager_linux-arm64.tar.gz"
      sha256 "f5575743e02c9eac36bbe1e112fe5e5da72f7e39c705a1d11ab7b3ac75970f0e"

      def install
        bin.install "gh-manager"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/gh-manager/releases/download/v0.2.0/gh-manager_linux-amd64.tar.gz"
      sha256 "852c93bba83cbd44b891be079a122aa8c48ba4c0ace1c99f1d6c37b94e1291f5"

      def install
        bin.install "gh-manager"
      end
    end
  end

  test do
    system "#{bin}/gh-manager version"
  end
end
